name: PR

on:
  pull_request:
    types: ['opened', 'synchronize']

env:
  CI: true

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Yarn
        run: yarn

      - name: Lint
        run: yarn lint

      - name: TypeCheck
        run: yarn check

      - name: Build
        run:  yarn build

      - name: Unit Test
        run:  yarn test
