name: Publish

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  release-prod:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: '(?<package>.*)_(?<version>.*)'

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Build
        run: yarn workspaces foreach -v -R --from ${{ steps.tagName.outputs.package }} run build

      - name: Lint
        run: |
          yarn workspace ${{ steps.tagName.outputs.package }} run lint

      - name: Test
        run: |
          yarn workspace ${{ steps.tagName.outputs.package }} run test

      - name: Authenticate with NPM
        run: |
          yarn config set npmAuthToken ${{ secrets.CDK_NPM_TOKEN }}

      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          NPM_TOKEN: ${{ secrets.CDK_NPM_TOKEN }}
        run: |
          yarn workspace ${{ steps.tagName.outputs.package }} run publish
